In [1]:
pip install faker

Collecting faker
  Downloading faker-40.21.0-py3-none-any.whl.metadata (16 kB)
Downloading faker-40.21.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 19.7 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.21.0

In [2]:
import pandas as pd
import numpy as np
from faker import Faker
import random
from datetime import datetime, timedelta

### Creating a users table

In [ ]:
fake = Faker()

users = []
for i in range(100):
  user = {
      "user_id": i + 1,
      "name": fake.name(),
      "email": fake.email(),
      "country": fake.country(),
      "signup_date": fake.date_between(start_date='-2y', end_date='today'),
      "subscription_type": random.choice(
          ["Free", "Premium", "Pro", "Enterprise"]
      )
  }
  users.append(user)

df1=pd.DataFrame(users)
df1

,user_id,name,email,country,signup_date,subscription_type
0,1,Mr. John Archer DVM,taylorwilson@example.net,Kyrgyz Republic,2024-10-03,Enterprise
1,2,Debbie Hays,holdermary@example.com,Central African Republic,2025-11-14,Pro
2,3,Amanda Gay,amycollier@example.org,Maldives,2025-08-28,Pro
3,4,Brandon Jensen,mcintyreseth@example.org,Lithuania,2024-06-24,Enterprise
4,5,Erin Morrow,hayeswendy@example.org,Swaziland,2025-09-13,Enterprise
...,...,...,...,...,...,...
95,96,Heather Rivera,anthony06@example.com,Tokelau,2025-09-20,Pro
96,97,Barbara Harris,rodriguezwilliam@example.com,United Arab Emirates,2025-04-14,Pro
97,98,Amanda Miles,charleswhite@example.net,Niger,2026-02-24,Enterprise
98,99,James Miller,ramirezsharon@example.com,Micronesia,2025-04-06,Pro
99,100,Catherine Jennings,johnsonlisa@example.com,Mongolia,2025-05-29,Premium

In [ ]:
people = []
for i in range(100000):
  person = {
      "person_id": i + 1,
      "name": fake.name(),
      "address": fake.address(),
      "city": fake.city(),
      "occupation": fake.job(),
      "email": fake.email(),
      "signup_date": fake.date_between(start_date='-2y', end_date='today'),
      "phone_number": fake.phone_number()
  }

  people.append(person)

df2=pd.DataFrame(people)
df2

,person_id,name,address,city,occupation,email,signup_date,phone_number
0,1,David Sullivan,"0098 Sonya Fields\nBenjaminfort, UT 61009",Charlesville,Trade mark attorney,hernandezmelissa@example.org,2024-07-20,(610)340-8387x3585
1,2,Julie Archer,"8779 Moore Forest\nNew Jessica, VI 39836",West Kimberlyfurt,Psychiatric nurse,riceshawn@example.com,2024-06-18,+1-276-592-7576
2,3,Morgan Castillo,"314 Torres Plain Suite 774\nKristinafort, VI 7...",Brendaview,"Radiographer, therapeutic",littletonya@example.com,2025-12-25,9717436279
3,4,Gregory Hines,"015 Amy Pines Apt. 163\nPiercefort, MH 42299",Port Anthonyhaven,Theatre director,marywillis@example.org,2025-01-14,001-731-981-7356
4,5,Kim Willis,"0845 Frost Mount\nWest Margaretfurt, IL 57625",Ashleyfurt,Architectural technologist,wcruz@example.com,2024-10-28,001-967-646-5517
...,...,...,...,...,...,...,...,...
99995,99996,Scott Bernard,"79421 Brent Loop Suite 781\nJuanland, NM 27950",New Andreashire,Clothing/textile technologist,gabrielle33@example.org,2024-11-22,737.497.0914x9803
99996,99997,Douglas Reynolds,"45640 Danielle Port Suite 917\nRebeccaburgh, V...",East Emilyborough,Contracting civil engineer,mary18@example.org,2026-01-05,735.480.9601x81783
99997,99998,Molly Jones,"9576 Sutton Avenue\nJonathanmouth, PR 82651",East Corey,Energy manager,florescraig@example.org,2025-05-19,646-644-2174x07407
99998,99999,Frank Harvey,"8621 Jackie Burgs\nPort Jessica, ID 18362",East Kaitlynville,"Administrator, local government",jeffreywhite@example.net,2024-12-31,+1-237-294-6294
99999,100000,Brian Stanley,"7039 Kevin Harbors Suite 755\nAlbertview, TN 6...",Deannashire,Ophthalmologist,glenn84@example.net,2024-08-28,816.458.0202x06085

In [ ]:
df2.to_csv('occupational_data', index=False)

# Creating a models table

In [ ]:
models = []

model_names = [
    "Random Forest Classifier",
    "Histogram Gradient Boosting",
    "Support Vector Machines",
    "Logistic Regression",
    "BERT",
    "DistilBERT"
]

for i in range(35):
  model={
      "model_ID": i + 1,
      "model_name": random.choice(model_names),
      "accuracy": round(random.uniform(0.60,0.99),2),
      "deployment_date": fake.date_between(start_date= '-1y', end_date = 'today')
  }

  models.append(model)

df3=pd.DataFrame(models)
df3

    model_ID                   model_name  accuracy deployment_date
0          1          Logistic Regression      0.77      2025-09-01
1          2     Random Forest Classifier      0.87      2025-06-20
2          3      Support Vector Machines      0.73      2025-10-15
3          4                         BERT      0.83      2025-08-15
4          5  Histogram Gradient Boosting      0.99      2025-05-23
5          6      Support Vector Machines      0.97      2026-03-18
6          7  Histogram Gradient Boosting      0.91      2025-11-11
7          8                         BERT      0.93      2026-04-15
8          9          Logistic Regression      0.92      2025-08-30
9         10     Random Forest Classifier      0.91      2026-05-18
10        11     Random Forest Classifier      0.72      2025-08-26
11        12      Support Vector Machines      0.96      2025-07-18
12        13          Logistic Regression      0.60      2026-05-19
13        14      Support Vector Machines      0.95      2026-04-22
14        15                   DistilBERT      0.68      2025-08-16
15        16                   DistilBERT      0.62      2025-12-23
16        17                         BERT      0.92      2025-11-20
17        18                   DistilBERT      0.89      2026-02-09
18        19  Histogram Gradient Boosting      0.77      2025-10-25
19        20     Random Forest Classifier      0.74      2026-05-18
20        21     Random Forest Classifier      0.65      2026-02-02
21        22      Support Vector Machines      0.61      2025-09-18
22        23          Logistic Regression      0.67      2026-02-15
23        24                         BERT      0.76      2026-03-14
24        25                         BERT      0.84      2025-06-05
25        26          Logistic Regression      0.64      2026-04-27
26        27     Random Forest Classifier      0.96      2026-02-05
27        28          Logistic Regression      0.94      2026-02-07
28        29          Logistic Regression      0.95      2025-09-22
29        30     Random Forest Classifier      0.73      2026-05-18
30        31     Random Forest Classifier      0.69      2025-10-07
31        32  Histogram Gradient Boosting      0.91      2025-07-07
32        33          Logistic Regression      0.60      2026-05-15
33        34     Random Forest Classifier      0.80      2025-08-10
34        35          Logistic Regression      0.77      2026-01-15

# Create an Inference Log table

In [ ]:
logs = []

for i in range(25):
  log={
      "log_id": i + 1,
      "user_id": random.randint(1,100),
      "model_id": random.randint(1,20),
      "latency_ms": random.randint(50, 2000),
      "request_time": fake.date_time_between(start_date= '-1y', end_date= 'now'),
      "success": random.choice(
          [True, False]
      )
  }

  logs.append(log)

  df4=pd.DataFrame(logs)

In [ ]:
df4

    log_id  user_id  model_id  latency_ms               request_time  success
0        1       17        10        1294 2026-02-10 22:15:41.971444    False
1        2       97        19         340 2025-08-26 21:51:30.459990     True
2        3       57         2        1903 2025-08-01 23:24:56.156485    False
3        4       30        14         568 2025-11-10 22:24:40.510865    False
4        5       45        14         271 2025-10-01 09:43:40.721215    False
5        6       43        18        1288 2026-03-22 15:37:37.801197     True
6        7       91        20         943 2026-05-09 20:12:01.780438    False
7        8       78        12        1587 2026-02-23 19:07:42.821472     True
8        9        8        13        1375 2025-08-10 18:25:23.679093     True
9       10       44        20          69 2026-05-15 05:15:46.553592    False
10      11       15         6        1979 2025-08-24 18:34:48.863843     True
11      12       50        11        1714 2025-10-16 12:43:22.974872    False
12      13       67        13        1933 2025-06-29 12:37:19.260845     True
13      14       44        12         334 2026-03-23 19:04:19.123229    False
14      15       19        16         632 2026-01-27 09:24:05.765653    False
15      16       46        11         718 2026-02-09 09:28:11.621902     True
16      17       12        16        1949 2025-10-18 18:59:46.736439    False
17      18       88         6        1498 2025-06-05 21:32:06.009871     True
18      19        3        16        1652 2026-01-03 16:09:04.300483     True
19      20        9         8         394 2026-02-01 12:14:27.827103    False
20      21       31         5         917 2025-11-30 22:42:29.718343    False
21      22       35         6          65 2025-07-28 01:36:34.677027    False
22      23       44         8        1652 2025-12-07 07:37:52.836388     True
23      24       24        18         905 2026-04-03 21:22:41.656393    False
24      25       30        19         343 2026-01-31 03:04:26.180253    False

In [ ]:
# Create a large dataset to predict student chances of graduation

data = []

for i in range(50):
  student = {
      "student_id": i + 1,
      "age": round(random.uniform(1,17), 0),
      "gender": random.choice(["Male", "Female"]),
      "socio_economic_score": random.choice(["Poor",
                                             "Lower_class",
                                             "Upper_middle_class",
                                             "Upper_class",
                                             "Wealthy"]),
      "attendance_rate": round(random.uniform(0, 100), 2),
      "average_assignment_score": random.randint(0,100),
      "midterm_exam_score": random.randint(0, 100),
      "final_exam_score": random.randint(0, 100),
      "study_hours_per_week": random.randint(0, 100),
      "lms_logins_per_week": random.randint(0, 100),
      "part_time_job_hours": random.randint(0, 100),
      "financial_aid": random.choice(["True", "False"]),
      "disciplinary_record": random.choice(
          [
          "None",
          "Moderate",
          "High"
      ]
          ),
      "graduation_outcome": random.choice(
          [
          "On_Time",
          "Delayed",
          "Dropout_Risk",
          "High_Achiever"
      ]
          )

  }

  data.append(student)

  df_=pd.DataFrame(data)

In [ ]:
df_

,student_id,age,gender,socio_economic_score,attendance_rate,average_assignment_score,midterm_exam_score,final_exam_score,study_hours_per_week,lms_logins_per_week,part_time_job_hours,financial_aid,disciplinary_record,graduation_outcome
0,1,11.0,Male,Upper_class,48.47,95,89,15,30,68,12,True,Moderate,On_Time
1,2,4.0,Male,Wealthy,18.49,5,56,82,69,21,13,False,Moderate,Dropout_Risk
2,3,5.0,Male,Wealthy,83.17,94,34,10,23,22,86,False,High,High_Achiever
3,4,3.0,Male,Poor,21.03,30,29,31,33,9,88,True,High,Delayed
4,5,10.0,Female,Upper_class,41.00,8,55,93,84,90,77,True,None,Delayed
5,6,1.0,Male,Upper_class,84.13,100,34,63,41,61,82,True,None,High_Achiever
6,7,1.0,Female,Wealthy,31.78,19,48,74,16,95,25,False,None,On_Time
7,8,4.0,Female,Upper_middle_class,20.43,75,21,46,91,86,87,False,None,Dropout_Risk
8,9,12.0,Female,Upper_middle_class,82.38,46,100,57,87,18,55,True,Moderate,On_Time
9,10,9.0,Male,Wealthy,81.14,66,45,28,21,26,17,True,Moderate,Dropout_Risk
10,11,7.0,Male,Lower_class,95.41,79,67,52,19,13,44,False,Moderate,Delayed
11,12,16.0,Female,Upper_class,89.58,33,90,20,100,85,16,True,None,Delayed
12,13,3.0,Female,Upper_class,81.52,36,38,69,56,73,89,True,None,High_Achiever
13,14,15.0,Female,Upper_class,27.10,62,55,55,27,37,58,True,None,Dropout_Risk
14,15,3.0,Female,Upper_middle_class,44.57,50,90,89,6,40,45,True,Moderate,Delayed
15,16,6.0,Female,Poor,81.47,60,19,60,60,1,66,False,High,Dropout_Risk
16,17,17.0,Male,Wealthy,72.96,66,17,62,48,25,85,True,Moderate,Dropout_Risk
17,18,3.0,Female,Poor,30.54,35,18,57,6,70,23,True,None,High_Achiever
18,19,15.0,Male,Lower_class,61.64,59,78,22,56,55,69,True,Moderate,High_Achiever
19,20,12.0,Male,Upper_middle_class,32.03,90,4,46,0,31,77,False,Moderate,On_Time
20,21,4.0,Female,Poor,34.55,50,72,35,85,17,55,True,Moderate,Delayed
21,22,10.0,Male,Poor,62.94,95,56,74,53,3,58,False,None,High_Achiever
22,23,9.0,Female,Upper_class,23.38,22,38,53,57,13,68,True,None,Dropout_Risk
23,24,7.0,Female,Lower_class,9.60,2,32,36,9,21,4,True,High,High_Achiever
24,25,7.0,Female,Wealthy,83.04,97,37,66,66,19,81,False,None,Dropout_Risk
25,26,3.0,Female,Upper_class,92.64,86,35,36,19,15,100,False,Moderate,Dropout_Risk
26,27,1.0,Male,Upper_middle_class,97.88,19,32,41,56,48,24,True,None,Dropout_Risk
27,28,4.0,Male,Wealthy,27.49,7,79,89,88,26,41,False,None,High_Achiever
28,29,6.0,Male,Lower_class,30.33,92,67,48,58,63,98,False,Moderate,Dropout_Risk
29,30,7.0,Female,Upper_middle_class,50.74,94,6,59,9,35,86,True,None,Delayed
30,31,8.0,Female,Upper_middle_class,70.49,19,93,2,17,25,60,False,High,Delayed
31,32,12.0,Female,Poor,4.34,79,78,15,51,69,43,False,High,On_Time
32,33,13.0,Male,Upper_middle_class,82.34,59,43,54,6,62,39,True,Moderate,High_Achiever
33,34,3.0,Male,Lower_class,7.04,67,9,12,36,54,28,False,Moderate,Dropout_Risk
34,35,17.0,Male,Poor,40.18,41,98,10,5,50,75,True,None,Delayed
35,36,4.0,Female,Lower_class,43.65,87,98,16,19,96,52,False,Moderate,Dropout_Risk
36,37,8.0,Female,Poor,5.22,29,98,52,18,81,50,True,High,On_Time
37,38,10.0,Female,Upper_class,93.24,36,29,68,48,50,8,False,None,Delayed
38,39,16.0,Male,Poor,7.77,70,24,98,68,93,62,False,Moderate,On_Time
39,40,11.0,Female,Poor,29.66,18,72,12,24,42,23,False,Moderate,High_Achiever
40,41,4.0,Male,Wealthy,1.70,90,58,67,80,74,9,False,Moderate,Dropout_Risk
41,42,8.0,Female,Upper_middle_class,79.92,50,78,66,65,19,70,True,High,Delayed
42,43,5.0,Male,Wealthy,19.48,95,92,27,7,72,61,True,Moderate,Delayed
43,44,4.0,Female,Wealthy,93.57,26,46,100,39,96,63,False,Moderate,Delayed
44,45,1.0,Male,Wealthy,51.26,37,65,54,16,24,60,True,Moderate,On_Time
45,46,8.0,Male,Wealthy,25.04,74,94,8,72,20,12,True,None,Dropout_Risk
46,47,7.0,Female,Wealthy,18.01,26,98,50,82,24,8,False,None,Dropout_Risk
47,48,14.0,Female,Wealthy,93.49,35,89,1,67,6,9,True,High,High_Achiever
48,49,16.0,Female,Poor,4.16,52,64,31,85,62,41,True,None,Delayed
49,50,15.0,Male,Upper_class,70.49,50,42,18,56,21,11,True,High,High_Achiever

In [ ]:
df_.shape

(50, 14)

In [ ]:
df_.columns

Index(['student_id', 'age', 'gender', 'socio_economic_score',
       'attendance_rate', 'average_assignment_score', 'midterm_exam_score',
       'final_exam_score', 'study_hours_per_week', 'lms_logins_per_week',
       'part_time_job_hours', 'financial_aid', 'disciplinary_record',
       'graduation_outcome'],
      dtype='object')

In [ ]:
df_.to_csv("student_data.csv")

## Data 1: Student Scholarship Qualification Data

In [3]:
data1=[]

for i in range(50):
  student1={
      "student_id": i + 1,
      "scholarship_eligible": random.choice(
          ['Yes', 'No']
      ),
      "scholarship_type": random.choice(
          ['Merit', 'Need-Based', 'Research', 'Leadership']
      ),
      "scholarship_amount": random.randint(1000, 100000),
      "scholarship_score": random.randint(100, 1000),
      "recommendation_status": random.choice(
          ['Pending', 'Approved', 'Rejected']
      ),
      "post_graduate_program": random.choice(
          ['Data Science', 'AI', 'UX', 'CyberSecurity', 'Civil Engineering', 'Architecture', 'Philosophy']
      )
  }

  data1.append(student1)

  df_join1=pd.DataFrame(data1)

In [4]:
 df_join1

,student_id,scholarship_eligible,scholarship_type,scholarship_amount,scholarship_score,recommendation_status,post_graduate_program
0,1,No,Need-Based,30716,536,Rejected,Architecture
1,2,Yes,Leadership,58279,296,Rejected,Architecture
2,3,Yes,Need-Based,33524,679,Rejected,AI
3,4,No,Research,48968,410,Approved,Philosophy
4,5,No,Research,86729,199,Rejected,AI
5,6,No,Need-Based,16049,157,Approved,Civil Engineering
6,7,No,Need-Based,94534,886,Rejected,Architecture
7,8,No,Leadership,32770,615,Approved,Architecture
8,9,No,Need-Based,62870,712,Rejected,AI
9,10,No,Merit,59655,974,Rejected,Civil Engineering
10,11,No,Research,27698,545,Approved,AI
11,12,No,Need-Based,78846,565,Approved,UX
12,13,Yes,Research,87827,559,Pending,Civil Engineering
13,14,No,Research,97491,985,Rejected,Data Science
14,15,No,Research,71950,480,Rejected,UX
15,16,Yes,Research,57166,311,Approved,Architecture
16,17,Yes,Research,41041,399,Rejected,Civil Engineering
17,18,No,Merit,54756,118,Pending,AI
18,19,Yes,Need-Based,94871,515,Pending,Philosophy
19,20,No,Merit,65351,879,Approved,Philosophy
20,21,No,Research,64428,561,Rejected,Philosophy
21,22,No,Merit,44844,767,Rejected,Philosophy
22,23,Yes,Merit,58896,886,Pending,CyberSecurity
23,24,No,Research,52650,383,Pending,UX
24,25,Yes,Need-Based,74935,576,Pending,Data Science
25,26,No,Need-Based,44829,886,Rejected,Architecture
26,27,No,Need-Based,2967,699,Approved,UX
27,28,No,Need-Based,56345,942,Rejected,Data Science
28,29,No,Need-Based,57259,575,Approved,AI
29,30,Yes,Need-Based,75238,754,Rejected,Philosophy
30,31,No,Leadership,55447,353,Pending,Philosophy
31,32,No,Need-Based,63656,828,Rejected,CyberSecurity
32,33,No,Leadership,89379,964,Rejected,UX
33,34,Yes,Leadership,26372,121,Rejected,Data Science
34,35,No,Need-Based,38800,634,Pending,Philosophy
35,36,Yes,Research,93879,474,Approved,AI
36,37,Yes,Need-Based,38258,473,Rejected,Philosophy
37,38,No,Research,56301,871,Rejected,Civil Engineering
38,39,No,Research,73742,878,Rejected,UX
39,40,Yes,Research,89967,486,Rejected,Philosophy
40,41,Yes,Need-Based,45373,331,Rejected,Civil Engineering
41,42,Yes,Merit,73353,256,Pending,Civil Engineering
42,43,No,Need-Based,86767,755,Pending,Civil Engineering
43,44,No,Leadership,33700,322,Approved,Architecture
44,45,No,Merit,90327,442,Pending,AI
45,46,No,Need-Based,36313,370,Approved,Architecture
46,47,Yes,Research,4089,387,Pending,Architecture
47,48,No,Merit,86036,840,Rejected,UX
48,49,Yes,Merit,52560,190,Approved,Architecture
49,50,No,Leadership,2501,872,Rejected,CyberSecurity

In [5]:
 df_join1.to_csv("student_scholarship_data.csv")

## Data 2: Student Career Outcomes Data

In [6]:
data2=[]

for i in range(50):
  student2={
      "student_id": i + 1,
      "career_path": random.choice(
          ['Data Science', 'AI', 'UX', 'CyberSecurity', 'Civil Engineering', 'Architecture', 'Philosophy']
      ),
      "employment_status": random.choice(
          ['Employed', 'Unemployed', 'Self-Employed']
      ),
      "industry": random.choice(
          ['Technology', 'Finance', 'Healthcare', 'Education', 'Manufacturing']
      ),
      "employment_type": random.choice(
          ['Full-Time', 'Part-Time', 'Contract']
      ),
      "starting_salary": random.randint(10000, 100000),
      "remote_work_availability": random.choice(
          ['Yes', 'No']
      ),
      "career_satisfaction_score": random.randint(1, 10)
  }

  data2.append(student2)

  df_join2=pd.DataFrame(data2)

In [7]:
df_join2

,student_id,career_path,employment_status,industry,employment_type,starting_salary,remote_work_availability,career_satisfaction_score
0,1,AI,Unemployed,Healthcare,Part-Time,82362,Yes,5
1,2,CyberSecurity,Unemployed,Manufacturing,Part-Time,81616,Yes,8
2,3,Architecture,Unemployed,Finance,Full-Time,79408,No,10
3,4,Architecture,Employed,Technology,Contract,16311,No,6
4,5,UX,Employed,Technology,Full-Time,31037,No,6
5,6,UX,Employed,Manufacturing,Part-Time,27028,Yes,8
6,7,CyberSecurity,Employed,Healthcare,Part-Time,23924,Yes,1
7,8,Architecture,Self-Employed,Education,Full-Time,28928,Yes,4
8,9,CyberSecurity,Self-Employed,Manufacturing,Contract,72170,Yes,10
9,10,Civil Engineering,Unemployed,Technology,Part-Time,10762,Yes,8
10,11,CyberSecurity,Employed,Healthcare,Part-Time,78747,Yes,3
11,12,Philosophy,Employed,Technology,Full-Time,41439,No,8
12,13,Civil Engineering,Employed,Manufacturing,Full-Time,98114,No,2
13,14,UX,Employed,Finance,Contract,51297,No,6
14,15,CyberSecurity,Unemployed,Finance,Full-Time,10533,No,2
15,16,Data Science,Self-Employed,Technology,Contract,91057,Yes,3
16,17,Philosophy,Self-Employed,Education,Contract,41548,No,9
17,18,Civil Engineering,Employed,Manufacturing,Contract,85293,Yes,8
18,19,Data Science,Employed,Manufacturing,Full-Time,45286,Yes,3
19,20,CyberSecurity,Self-Employed,Finance,Full-Time,42300,No,10
20,21,UX,Employed,Finance,Part-Time,39300,No,4
21,22,CyberSecurity,Unemployed,Finance,Full-Time,84978,No,4
22,23,UX,Self-Employed,Education,Contract,35923,Yes,5
23,24,CyberSecurity,Employed,Manufacturing,Full-Time,54302,No,10
24,25,Civil Engineering,Self-Employed,Technology,Part-Time,72070,Yes,9
25,26,AI,Unemployed,Manufacturing,Contract,87000,Yes,6
26,27,AI,Employed,Finance,Full-Time,88655,Yes,6
27,28,Data Science,Self-Employed,Finance,Part-Time,56421,No,7
28,29,Architecture,Self-Employed,Finance,Part-Time,11395,Yes,4
29,30,Data Science,Unemployed,Finance,Full-Time,90096,No,1
30,31,CyberSecurity,Unemployed,Finance,Part-Time,71735,Yes,5
31,32,Data Science,Employed,Manufacturing,Part-Time,71244,No,7
32,33,Architecture,Employed,Education,Part-Time,30224,No,1
33,34,UX,Employed,Manufacturing,Full-Time,37542,No,10
34,35,Civil Engineering,Unemployed,Finance,Contract,67931,No,2
35,36,Architecture,Employed,Technology,Part-Time,28176,Yes,10
36,37,Philosophy,Employed,Technology,Part-Time,81777,Yes,2
37,38,Architecture,Unemployed,Education,Full-Time,59037,Yes,4
38,39,Philosophy,Self-Employed,Manufacturing,Contract,34987,Yes,5
39,40,CyberSecurity,Self-Employed,Healthcare,Full-Time,23262,No,2
40,41,Architecture,Self-Employed,Education,Part-Time,51991,Yes,6
41,42,Civil Engineering,Self-Employed,Finance,Part-Time,72549,No,2
42,43,Philosophy,Employed,Education,Part-Time,14535,Yes,1
43,44,Data Science,Self-Employed,Healthcare,Part-Time,25301,Yes,9
44,45,AI,Unemployed,Manufacturing,Full-Time,75268,No,10
45,46,Civil Engineering,Self-Employed,Technology,Part-Time,47484,Yes,8
46,47,AI,Self-Employed,Healthcare,Full-Time,25319,No,2
47,48,AI,Employed,Education,Part-Time,96424,No,6
48,49,Civil Engineering,Unemployed,Manufacturing,Full-Time,65310,Yes,10
49,50,AI,Employed,Education,Full-Time,67446,No,9

In [8]:
df_join2.to_csv("student_career_data.csv")